language: python
python:
  - "2.7"
before_install:
# We need this line to have g++4.8 available in apt
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
# command to install dependencies
install:
  - "sudo apt-get install -qq gcc-4.8 g++-4.8"
  # We want to compile with g++ 4.8 when rather than the default g++
  - "sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90"
  - "sudo apt-get install swig"
  - "pip install numpy"
  - cd src/python
  - "python setup.py install"
  - "cd ../../include/cvxpy"
  - "python setup.py install"
  - "cd ../../"

# command to run tests
script:  "python tests/python/test_linops.py"