language: python
python:
  - "2.7"
os:
  - linux
#  - osx
before_install:
  # Install conda to avoid a lengthy build process from scipy and numpy 
  # binaries (CVXCanon will automatically build NUMPY from 
  # source if needed. SCIPY is only used by cvxpy, but building from 
  # source for each build is too slow)
  - sudo pip install conda
  # install deps
  - sudo conda init
  - deps='pip numpy scipy'
  - conda create -p $HOME/py --yes $deps "python=$TRAVIS_PYTHON_VERSION"
  - export PATH=$HOME/py/bin:$PATH

  # cvxpy dependency 
  - sudo apt-get install -qq libatlas-base-dev gfortran
  - export ATLAS="/usr/lib/atlas-base/libatlas.so"

# command to install dependencies
install:
  # TODO: MAKE THIS LINE UNECESSARY (modify setup.py to handle swig installation)
 # - "sudo apt-get install swig"

  # # compiling library
  # - "python setup.py install"
  #- "pip install CVXcanon"

  # adding cvxpy 
  - "cd tests"
  - "git clone https://github.com/cvxgrp/cvxpy.git"
  - "cd cvxpy"
  - "git checkout develop"
  - "python setup.py install"
  - "pip install nose"

# command to run tests
script:  "nosetests cvxpy"

notifications:
  email: false