language: python
python:
  - "2.7"
before_install:
# We need this line to have g++4.8 available in apt
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
# command to install dependencies
install:
  # compiler dependencies
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  # wrapper code
  - "sudo apt-get install swig"
  - "pip install numpy"
  # adding cvxpy 
  - "cd include"
  - "git clone https://github.com/jacklzhu/cvxpy.git"
  - "cd cvxpy"
  - "python setup.py install"
  # compiling library
  - "cd ../../src/python"
  - "python setup.py install"
  - "cd ../../"

# command to run tests
script:  "python tests/python/test_linops.py"